apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: udacityshop-dev
  namespace: dev
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kubernetes-manifests/dev
    repoURL: https://github.com/nkordis/udacity-shop/
    targetRevision: HEAD
  syncPolicy:
    automated: {}